### ISSUE TITLE
[FE] 프로젝트 중간 점검

### ISSUE THREAD

**Issue by seungdeng17** [codesquad-member-2020/todo-10#72]
- [x] 분업 작업 브랜치 -> dev 머지
- [x] 함수, 변수명 리팩토링
- [x] 상수 분리
- [x] 템플레이트 유틸 작성

**Comment by 77unny** [comment]
@baekCode 해야할것!
- 스타일링 수정 (부분적으로 버그가 보임)
- 함수, 변수명 리팩토링 (공통적인 코드 정리)
- 템플레이팅 작성
